version = 0.1

[default.deploy.parameters]
stack_name = "tripwiz"
resolve_s3 = true
s3_prefix = "tripwiz"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AdminEmail=\"amituniversitymail@gmail.com\" SourceEmail=\"amituniversitymail@gmail.com\" AdminBootstrapEmails=\"amituniversitymail@gmail.com,davidkitinberg@gmail.com\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"

[david.deploy.parameters]
stack_name = "tripwiz"
resolve_s3 = true
s3_prefix = "tripwiz"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AdminEmail=\"davidkitinberg@gmail.com\" SourceEmail=\"davidkitinberg@gmail.com\" AdminBootstrapEmails=\"davidkitinberg@gmail.com\""
image_repositories = []

[david.global.parameters]
region = "us-east-1"
